import { assert, test, sequence } from './harness';
import { generateProblem } from '../src/engine/generator';
import { ADDITION_1_DIGIT, ADDITION_2_DIGIT, ADDITION_2_DIGIT_CARRYING, SUBTRACTION_1_DIGIT, SUBTRACTION_2_DIGIT, SUBTRACTION_2_DIGIT_BORROWING, MULTIPLICATION_FACTS, DIVISION_FACTS, DIVISION_REMAINDERS, MIXED_PRACTICE, multiplyTableConfig, divideByConfig } from '../src/engine/presets';
const withRandom = <T>(fn:()=>number, run:()=>T) => { const old=Math.random; Math.random=fn; try{return run();}finally{Math.random=old;} };
const carry=(a:number,b:number)=>{while(a||b){if(a%10+b%10>=10)return true;a=Math.floor(a/10);b=Math.floor(b/10)}return false};
const borrow=(a:number,b:number)=>{while(a||b){if(a%10<b%10)return true;a=Math.floor(a/10);b=Math.floor(b/10)}return false};
export const tests = [
 test('addition presets preserve bounds, sums, and regrouping constraints', () => {
   for(const config of [ADDITION_1_DIGIT,ADDITION_2_DIGIT]) withRandom(()=>0,()=>{const p=generateProblem(config);assert.equal(p.operation,'addition');assert.equal(p.correctAnswer,p.operandA+p.operandB);assert.ok(p.operandA>=config.operandA.min&&p.operandA<=config.operandA.max);assert.ok(p.operandB>=config.operandB.min&&p.operandB<=config.operandB.max);if(config.carrying===false)assert.equal(carry(p.operandA,p.operandB),false)});
   withRandom(()=>.95,()=>{const config=ADDITION_2_DIGIT_CARRYING,p=generateProblem(config);assert.equal(p.correctAnswer,p.operandA+p.operandB);assert.ok(p.operandA>=config.operandA.min&&p.operandA<=config.operandA.max);assert.ok(p.operandB>=config.operandB.min&&p.operandB<=config.operandB.max);assert.ok(carry(p.operandA,p.operandB));assert.ok(p.operandA%10+p.operandB%10>=10)});
 }),
 test('one-digit addition suppresses immediate problem and third repeated answer',()=>withRandom(sequence([0,0, 0,0,.2,0, .1,.1,.3,0]),()=>{const c={...ADDITION_1_DIGIT,storageKey:'repeat-contract'};const a=generateProblem(c),b=generateProblem(c),d=generateProblem(c);assert.notDeepEqual([b.operandA,b.operandB],[a.operandA,a.operandB]);assert.ok(!(a.correctAnswer===b.correctAnswer&&b.correctAnswer===d.correctAnswer))})),
 test('subtraction guarantees nonnegative answers and borrowing mode',()=>withRandom(()=>.73,()=>{for(const c of [SUBTRACTION_1_DIGIT,SUBTRACTION_2_DIGIT,SUBTRACTION_2_DIGIT_BORROWING]){const p=generateProblem(c);assert.ok(p.operandA>=p.operandB);assert.equal(p.correctAnswer,p.operandA-p.operandB);assert.equal(borrow(p.operandA,p.operandB),c.borrowing===true)}})),
 test('subtraction exhaustively falls back and throws for impossible configurations',()=>withRandom(()=>0,()=>{const p=generateProblem({...SUBTRACTION_2_DIGIT_BORROWING,storageKey:'fallback',operandA:{min:20,max:21},operandB:{min:11,max:19}});assert.deepEqual([p.operandA,p.operandB],[20,11]);assert.throws(()=>generateProblem({...SUBTRACTION_1_DIGIT,storageKey:'impossible',operandA:{min:1,max:1},operandB:{min:2,max:2}}),/Unable to generate subtraction problem/)})),
 test('multiplication facts and all twelve table identities are exact',()=>withRandom(()=>.5,()=>{const f=generateProblem(MULTIPLICATION_FACTS);assert.ok(f.operandA>=1&&f.operandA<=12);assert.equal(f.correctAnswer,f.operandA*f.operandB);for(let n=1;n<=12;n++){const c=multiplyTableConfig(n),p=generateProblem(c);assert.equal(p.operandA,n);assert.ok(p.operandB>=1&&p.operandB<=12);assert.equal(p.correctAnswer,n*p.operandB);assert.equal(c.storageKey,`mult-table-${n}`);assert.equal(c.path,`/multiplication/times-tables/${n}/`)}})),
 test('division facts and all twelve divide-by identities divide exactly',()=>withRandom(()=>.5,()=>{for(const c of [DIVISION_FACTS,...Array.from({length:12},(_,i)=>divideByConfig(i+1))]){const p=generateProblem(c);assert.equal(p.operation,'division');assert.equal(p.remainder,undefined);assert.equal(p.operandA,p.operandB*p.correctAnswer)}for(let n=1;n<=12;n++){const c=divideByConfig(n),p=generateProblem(c);assert.equal(p.operandB,n);assert.equal(c.storageKey,`div-by-${n}`);assert.equal(c.path,`/division/divide-by/${n}/`)}})),
 test('remainder generation uses its fixed production ranges and answer representation',()=>withRandom(()=>.999,()=>{const p=generateProblem({...DIVISION_REMAINDERS,operandA:{min:999,max:999},operandB:{min:99,max:99}});assert.ok(p.operandB>=2&&p.operandB<=12);assert.ok(p.correctAnswer>=1&&p.correctAnswer<=12);assert.ok(p.remainder!>=1&&p.remainder!<p.operandB);assert.equal(p.operandA,p.operandB*p.correctAnswer+p.remainder!)})),
 test('mixed operation selection follows controlled allowlists and current defaults',()=>{const expected=['addition','subtraction','multiplication','division'];expected.forEach((op,i)=>withRandom(sequence([i/4,.5,.5]),()=>assert.equal(generateProblem({...MIXED_PRACTICE,storageKey:`mixed-${i}`}).operation,op)));for(const op of expected)withRandom(()=>.5,()=>assert.equal(generateProblem({...MIXED_PRACTICE,storageKey:`only-${op}`,operations:[op as any]}).operation,op));assert.deepEqual(MIXED_PRACTICE.operations,expected)})
];
