import { assert, test } from './harness';
import { readFileSync, existsSync } from 'node:fs';
import { TIMES_TABLE_FACTS } from '../src/data/generated-practice/timesTables';
import { DIVIDE_BY_FACTS } from '../src/data/generated-practice/divideBy';
const source=(p:string)=>readFileSync(p,'utf8');
export const tests=[
 test('generated static families contain exactly the canonical 1–12 entries',()=>{assert.deepEqual(TIMES_TABLE_FACTS.map(x=>x.n),Array.from({length:12},(_,i)=>i+1));assert.deepEqual(DIVIDE_BY_FACTS.map(x=>x.n),Array.from({length:12},(_,i)=>i+1));assert.ok(existsSync('src/pages/multiplication/times-tables/[table].astro'));assert.ok(existsSync('src/pages/division/divide-by/[divisor].astro'))}),
 test('protected route families and worksheet/grade/progress pages remain present',()=>{for(const p of ['addition/index.astro','addition/1-digit.astro','addition/2-digit-without-regrouping.astro','addition/2-digit-with-regrouping.astro','subtraction/index.astro','subtraction/1-digit.astro','subtraction/2-digit-without-regrouping.astro','subtraction/2-digit-with-regrouping.astro','multiplication/index.astro','multiplication/facts.astro','multiplication/times-tables/index.astro','multiplication-chart/index.astro','division/index.astro','division/divide-by/index.astro','division/facts.astro','division/remainders.astro','arithmetic-speed-drill.astro','math-facts.astro','progress.astro','math-worksheets/index.astro','1st-grade-math-practice.astro','5th-grade-math-practice.astro','daily-review/index.astro'])assert.ok(existsSync(`src/pages/${p}`),p)}),
 test('Daily Review is discoverable from the homepage, For Teachers, and every grade page without a header slot',()=>{const home=source('src/pages/index.astro'),teachers=source('src/pages/for-teachers.astro'),header=source('src/components/SiteHeader.astro');assert.ok(home.includes('href="/daily-review/"'),'homepage must link to Daily Review');assert.ok(teachers.includes("/daily-review/"),'For Teachers must link to Daily Review');assert.equal(header.includes('/daily-review/'),false,'Daily Review must not get a new global-header slot in V1');for(const [file,grade] of [['1st-grade-math-practice.astro','g1'],['2nd-grade-math-practice.astro','g2'],['3rd-grade-math-practice.astro','g3'],['4th-grade-math-practice.astro','g4'],['5th-grade-math-practice.astro','g5']]as const)assert.ok(source(`src/pages/${file}`).includes(`/daily-review/?grade=${grade}`),`${file} must link to its own grade-prefilled Daily Review`)}),
 test('widget lifecycle preserves first-answer timer, feedback guards, delays, completion and replay',()=>{const s=source('src/components/PracticeWidget.tsx');for(const fragment of ["if (!problem || phase !== 'active') return","if (isTimed && !timerStartedRef.current)","setTimerStarted(true)","setInterval(() =>","if (s <= 1)","endSession()","if (transitionTimerRef.current) clearTimeout","config.correctFeedbackDelayMs ?? 600","config.incorrectFeedbackDelayMs ?? 1800","setProblem(getProblemAt(0))","function handleRestart()","setSecondsRemaining(duration)","recordCompletedQuestion(sessionBoundaryRef.current, questionCount)","finishAnswerFeedback(sessionBoundaryRef.current)","expirePracticeTimer(sessionBoundaryRef.current)"])assert.ok(s.includes(fragment),fragment)}),
 test('a prebuilt problems array bypasses random generation entirely and remainder rendering is problem-driven, not config-driven',()=>{const s=source('src/components/PracticeWidget.tsx');assert.ok(s.includes('problems?: Problem[]'),'PracticeWidget must accept an optional prebuilt problems array');assert.ok(s.includes('function getProblemAt(index: number)'),'problem lookup must go through a single indexing helper');assert.ok(s.includes('if (!problems || problems.length === 0) return generateProblem(config)'),'generateProblem must remain the fallback only when no prebuilt array is supplied');assert.ok(s.includes('setProblem(getProblemAt(totalAnsweredRef.current))'),'advancing to the next problem must index into the prebuilt array using the same completed-question count session.ts already tracks');assert.equal(s.includes('config.withRemainder'),false,'remainder-input rendering must no longer read the session-wide config; both call sites must derive from the current problem instead');assert.ok(s.includes('showRemainder={problem.remainder !== undefined}'),'prototype long-division remainder field must be driven by the current problem');assert.ok(s.includes('problem.remainder !== undefined ? (\n              <RemainderProblemInput'),'classic remainder-vs-written input choice must be driven by the current problem')}),
 test('shared runner uses the same current practice surface path as canonical skills',()=>{const runner=source('src/components/SharedPracticeRunner.tsx'), route=source('src/pages/practice.astro');assert.ok(runner.includes('variant="prototype"'));assert.ok(route.includes("import '@/styles/practice-surface-prototype.css'"));assert.equal(runner.includes('variant="classic"'),false)}),
 test('shared runner explicitly opts out of streak mechanics while canonical widgets keep the default',()=>{const runner=source('src/components/SharedPracticeRunner.tsx'),widget=source('src/components/PracticeWidget.tsx');assert.ok(runner.includes('sessionPresentation="shared"'));assert.ok(widget.includes("sessionPresentation = 'canonical'"));assert.ok(widget.includes('!isTimed && trackStreaks'));assert.ok(widget.includes('updateStatsAfterUntimedAnswer(currentStats, isCorrect, trackStreaks)'))}),
 test('the active timed Personal Best display is gated on the same trackStreaks flag as untimed streaks, not on route or presentation string checks',()=>{const widget=source('src/components/PracticeWidget.tsx');assert.ok(widget.includes('isTimed && trackStreaks'),'timed Personal Best row must read trackStreaks so shared sessions (sessionPresentation !== "canonical") hide it the same way untimed shared sessions already hide streaks');assert.equal(widget.includes("sessionPresentation === 'shared'"),false,'gating should stay on the existing trackStreaks derivation, not a new route/presentation-string check scattered through the render')}),
 test('input contracts retain keyboard, keypad, focus and remainder requirements',()=>{const written=source('src/components/WrittenProblemInput.tsx'), remainder=source('src/components/RemainderProblemInput.tsx'), pad=source('src/components/NumberPad.tsx'), long=source('src/components/LongDivisionProblemInput.tsx');assert.ok(written.includes("e.key === 'Enter'"));assert.ok(written.includes('inputRef.current?.focus()'));for(const x of ["['7', '8', '9']",'onMouseDown={prevent}','aria-label="Backspace"','aria-label="Submit answer"'])assert.ok(pad.includes(x));for(const x of ["setActiveSlot('quotient')","setActiveSlot('remainder')","isNaN(q) || isNaN(r)","e.key === 'Enter'",'inputRef.current?.focus()'])assert.ok(remainder.includes(x));for(const x of ['divided by','Enter quotient','showRemainder','onKeyDown'])assert.ok(long.includes(x))}),
 test('family-level Times Tables links point to the /multiplication/times-tables/ hub, not the 1 leaf',()=>{const home=source('src/pages/index.astro'),hub=source('src/pages/multiplication/index.astro'),facts=source('src/pages/multiplication/facts.astro');assert.ok(hub.includes("href: '/multiplication/times-tables/',\n    label: 'Times Tables 1–12',"),'multiplication hub primary mode card must link the whole family to the hub');assert.equal((home.match(/href="\/multiplication\/times-tables\/1\/"/g)||[]).length,0,'homepage should not link "Times Tables 1–12" cards to the 1 leaf');assert.ok(home.includes('href="/multiplication/times-tables/" class="text-sm font-semibold text-[#7C3AED]'),'2nd-3rd grade card Times Tables 1–12 link must point to the hub');assert.ok(home.includes('href="/multiplication/times-tables/" class="text-sm font-semibold text-[#059669]'),'4th-5th grade card Times Tables 1–12 link must point to the hub');assert.ok(home.includes('<a href="/multiplication/times-tables/" class="text-sm text-[#059669]'),'homepage footer Times Tables (1–12) link must point to the hub');assert.ok(facts.includes("{ href: '/multiplication/times-tables/', label: 'Times Tables Practice'"),'multiplication facts related link must point to the hub');assert.ok(facts.includes('href="/multiplication/times-tables/" class="text-[#4F46E5] font-semibold'),'multiplication facts inline CTA must point to the hub')}),
 test('genuine specific-leaf Times Tables links remain untouched',()=>{const teachers=source('src/pages/for-teachers.astro'),hub=source('src/pages/multiplication/index.astro'),table=source('src/pages/multiplication/times-tables/[table].astro');assert.ok(teachers.includes('href="/multiplication/times-tables/1/" class="text-[#4F46E5] hover:underline">times tables one at a time'),'for-teachers entry-flow CTA should still launch the 1 leaf');assert.ok(hub.includes('href="/multiplication/times-tables/2/"'),'multiplication hub tips prose should still cite the 2 leaf');assert.ok(hub.includes('href="/multiplication/times-tables/9/"'),'multiplication hub tips prose should still cite the 9 leaf');assert.ok(table.includes("{ label: 'Times Tables', href: '/multiplication/times-tables/' }"),'each times table leaf breadcrumb must still link back to the hub')})
];
