import { assert, test } from './harness';
import { scoreAnswer, calculateSessionScore, calculateTimedScore, buildSessionResult } from '../src/engine/scorer';
import * as presets from '../src/engine/presets';
export const tests=[
 test('ordinary and quotient/remainder scoring is exact',()=>{const p={id:'1',operandA:7,operandB:2,operation:'division' as const,correctAnswer:3,remainder:1};assert.equal(scoreAnswer({...p,remainder:undefined},3),true);assert.equal(scoreAnswer({...p,remainder:undefined},4),false);assert.equal(scoreAnswer(p,3,1),true);assert.equal(scoreAnswer(p,2,1),false);assert.equal(scoreAnswer(p,3,0),false)}),
 test('accuracy and timed normalization preserve zero and rounding semantics',()=>{assert.equal(calculateSessionScore(0,0),0);assert.equal(calculateSessionScore(2,3),67);assert.equal(calculateTimedScore(0,0),0);assert.equal(calculateTimedScore(7,30),14)}),
 test('session result uses supplied values and current ISO time',()=>{const RealDate=Date;globalThis.Date=class extends RealDate{constructor(...a:any[]){super(...(a.length?a:['2026-01-02T03:04:05.000Z']) as [any])}static now(){return new RealDate('2026-01-02T03:04:05Z').valueOf()}} as DateConstructor;try{assert.deepEqual(buildSessionResult(2,3,60),{correct:2,total:3,durationSeconds:60,score:67,timestamp:'2026-01-02T03:04:05.000Z'})}finally{globalThis.Date=RealDate}}),
 test('material preset configuration remains stable',()=>{assert.deepEqual([presets.ADDITION_1_DIGIT.storageKey,presets.ADDITION_2_DIGIT.carrying,presets.ADDITION_2_DIGIT_CARRYING.requireOnesRegroup],['add-1d',false,true]);assert.deepEqual([presets.SUBTRACTION_1_DIGIT.borrowing,presets.SUBTRACTION_2_DIGIT.borrowing,presets.SUBTRACTION_2_DIGIT_BORROWING.borrowing],[false,false,true]);assert.deepEqual([presets.MULTIPLICATION_FACTS.factsMode,presets.MULTIPLICATION_FACTS.maxFactor,presets.DIVISION_FACTS.storageKey],[true,12,'div-facts']);assert.deepEqual([presets.DIVISION_REMAINDERS.withRemainder,presets.DIVISION_REMAINDERS.incorrectFeedbackDelayMs],[true,3500]);assert.deepEqual(presets.ARITHMETIC_SPEED_DRILL,{storageKey:'speed-drill',label:'Arithmetic Speed Drill',path:'/arithmetic-speed-drill',operation:'mixed',mode:'timed',timerDuration:60,fixedTimerDuration:true,operandA:{min:1,max:12},operandB:{min:1,max:12},operations:['addition','subtraction','multiplication','division'],factsMode:true,correctFeedbackDelayMs:200,incorrectFeedbackDelayMs:400})})
];
