import { assert, test } from './harness';
import { DEFAULT_STATS, loadStats, saveStats, clearStats, clearAllProgress, updateStatsAfterSession, resetCurrentStreak, resetLongestStreak, resetPersonalBestScore, loadSessionLog, appendSessionLog, MODE_PREF_KEY, DURATION_PREF_KEY } from '../src/engine/storage';
class MemoryStorage { data=new Map<string,string>(); get length(){return this.data.size} key(i:number){return [...this.data.keys()][i]??null} getItem(k:string){return this.data.get(k)??null} setItem(k:string,v:string){this.data.set(k,String(v))} removeItem(k:string){this.data.delete(k)} clear(){this.data.clear()} }
const setup=()=>{const s=new MemoryStorage();Object.defineProperty(globalThis,'localStorage',{value:s,writable:true,configurable:true});return s};
const stats={...DEFAULT_STATS,currentStreak:4,longestStreak:8,bestTimedScore:12,personalBestScore:10,lastSessionScore:50,lastSessionDate:'old',totalProblemsAttempted:20,totalSessions:2};
const entry=(n:number)=>({storageKey:`s${n}`,label:`S ${n}`,correct:n,total:n+1,score:50,durationSeconds:60,isTimed:true,timestamp:`t${n}`});
export const tests=[
 test('storage key constants and missing, partial, malformed records are characterized',()=>{const s=setup();assert.equal(MODE_PREF_KEY,'mp_mode_pref');assert.equal(DURATION_PREF_KEY,'mp_duration_pref');assert.deepEqual(loadStats('none'),DEFAULT_STATS);s.setItem('mp_stats_partial','{"currentStreak":3}');assert.deepEqual(loadStats('partial'),{...DEFAULT_STATS,currentStreak:3});s.setItem('mp_stats_bad','{');assert.deepEqual(loadStats('bad'),DEFAULT_STATS)}),
 test('stats round trip and individual reset helpers preserve their scopes',()=>{setup();saveStats('x',stats);assert.deepEqual(loadStats('x'),stats);resetCurrentStreak('x');assert.equal(loadStats('x').currentStreak,0);assert.equal(loadStats('x').longestStreak,8);resetLongestStreak('x');assert.equal(loadStats('x').longestStreak,0);resetPersonalBestScore('x');assert.equal(loadStats('x').personalBestScore,0);assert.equal(loadStats('x').bestTimedScore,0);clearStats('x');assert.deepEqual(loadStats('x'),DEFAULT_STATS)}),
 test('timed and untimed session updates preserve current score and best semantics',()=>{setup();const result={correct:8,total:10,durationSeconds:30,score:80,timestamp:'x'};const timed=updateStatsAfterSession(stats,result,true);assert.deepEqual([timed.bestTimedScore,timed.personalBestScore,timed.lastSessionScore,timed.totalProblemsAttempted,timed.totalSessions],[16,10,80,30,3]);const untimed=updateStatsAfterSession(stats,result,false);assert.deepEqual([untimed.bestTimedScore,untimed.personalBestScore],[12,10]);assert.deepEqual([untimed.currentStreak,untimed.longestStreak],[4,8])}),
 test('session log appends in order and retains the latest fifty',()=>{setup();for(let i=0;i<55;i++)appendSessionLog(entry(i));const log=loadSessionLog();assert.equal(log.length,50);assert.equal(log[0].storageKey,'s5');assert.equal(log[49].storageKey,'s54')}),
 test('clear all removes only stats and session log, preserving preferences and unrelated data',()=>{const s=setup();s.setItem('mp_stats_a','{}');s.setItem('mp_session_log','[]');s.setItem(MODE_PREF_KEY,'timed');s.setItem(DURATION_PREF_KEY,'120');s.setItem('other','yes');clearAllProgress();assert.equal(s.getItem('mp_stats_a'),null);assert.equal(s.getItem('mp_session_log'),null);assert.equal(s.getItem(MODE_PREF_KEY),'timed');assert.equal(s.getItem('other'),'yes')}),
 test('storage read/write/quota exceptions are swallowed',()=>{setup();Object.defineProperty(globalThis,'localStorage',{value:{getItem(){throw Error('blocked')},setItem(){throw Error('quota')},removeItem(){throw Error('blocked')},get length(){throw Error('blocked')},key(){return null}},configurable:true});assert.deepEqual(loadStats('x'),DEFAULT_STATS);assert.doesNotThrow(()=>saveStats('x',stats));assert.doesNotThrow(()=>clearStats('x'));assert.doesNotThrow(clearAllProgress);assert.deepEqual(loadSessionLog(),[]);assert.doesNotThrow(()=>appendSessionLog(entry(1)))})
];
